# Generated by Django 4.1.7 on 2023-03-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=60)),
                ('about', models.TextField()),
                ('avgrating', models.DecimalField(decimal_places=10, max_digits=15)),
                ('behaviour', models.IntegerField()),
                ('toiletandcleanliness', models.IntegerField()),
                ('inhousestay', models.BooleanField()),
                ('disableperson_friendly', models.BooleanField()),
                ('medical_emergency', models.BooleanField()),
                ('food_facility', models.IntegerField()),
                ('opstarting', models.TimeField()),
                ('opending', models.TimeField()),
                ('working_days', models.CharField(default='SMTWTFS', max_length=30)),
                ('feechild', models.FloatField()),
                ('feeadult', models.FloatField()),
                ('feeforeigner', models.FloatField()),
                ('feestudent', models.FloatField()),
            ],
        ),
    ]
