# Generated by Django 4.1.7 on 2023-03-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
